spring.application.name=Tienda
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tienda
spring.datasource.username=root
spring.datasource.password=MySQL2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
